### ISSUE TITLE
Bagian Home/What's Next , tidak bekerja maksimal

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#1]
**Bagian Home/What's Next , tidak bekerja maksimal**

![screen shot 2019-03-04 at 22 55 08](https://user-images.githubusercontent.com/48216452/53744937-a1316780-3ed0-11e9-843c-68c8bc6cb5aa.png)

Secara front end agak kacau, mungkin salah ambil html css , soalnya setahu ku front yang kemarin beres

lalu ...

![screen shot 2019-03-04 at 22 59 17](https://user-images.githubusercontent.com/48216452/53745276-48ae9a00-3ed1-11e9-8b76-e49fe187c72e.png)

Secara back end, di dashboard belum tercantum fitur What's Next

Fitur Whats Next adalah Tema editors letter per bulan , modelnya **sama kayak Artikel pada umumnya**

**Comment by rynzvl** [comment]
untuk foto sudah oke sesuai email yang dikirim kemarin fotonya, terus fitur whats next emang belum radinal nanti setelah fitur articlenya beres kita barusan bkin whats next nya dengan template fitur article yang sudah jadi.. biar tidak 2x kerja ngubah di bnyk tempat

**Comment by radinalsuryaatmaja** [comment]
Oke SIAP
