### ISSUE TITLE
As user - Request - Pop Up before SUBMIT article to admin

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#10]
Jadi ketika user mau SUBMIT article , diberi pop up

" Apakah Anda sudah yakin ingin mengirimkan artikel ini ? "
Yes - No

---

ini dibuat untuk meyakinkan user , karena setelah artikel dikirim, ibarat kirim email , tidak bisa di edit edit lagi artikelnya

**Comment by rynzvl** [comment]
done, tolong "close" jika sudah sesuai dengan yang diharapkan

**Comment by radinalsuryaatmaja** [comment]
DONE
