### ISSUE TITLE
Mengganti Urutan Kategori saat create article

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#11]
Yang sekarang:

![Screen Shot 2019-03-12 at 11 12 22](https://user-images.githubusercontent.com/48216452/54174197-de40bf80-44b7-11e9-8bb0-10d7c43cf7ed.png)

Diharapkan urutannya

[Kategori - sub kategori]

Contoh

**BEST REGARDS // Live Through This
GOING DEEPER // God's Word**

*pakai " // " untuk memisahkan antara kategori dan sub kategori

**Comment by rynzvl** [comment]
fixed, minta di "close and comment" kalau sudah benar ya, thanks

**Comment by radinalsuryaatmaja** [comment]
OKE Benar
