### ISSUE TITLE
As User - Error Bug - Preview Article saat di Draft

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#12]
sudah di draft

![Screen Shot 2019-03-12 at 11 48 39](https://user-images.githubusercontent.com/48216452/54175338-1ac2ea00-44bd-11e9-9f47-b902d0139613.png)

Ketika di preview

![Screen Shot 2019-03-12 at 11 48 45](https://user-images.githubusercontent.com/48216452/54175341-1f879e00-44bd-11e9-8aa7-6e35360acce7.png)

**Comment by rynzvl** [comment]
fixed, minta tolong di "close" jika sudah benar

**Comment by radinalsuryaatmaja** [comment]
done
