### ISSUE TITLE
As user - Thumbnail article di draft beda dengan preview article

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#13]
Ini thumbnailnya

![Screen Shot 2019-03-12 at 15 46 55](https://user-images.githubusercontent.com/48216452/54186528-32f73100-44de-11e9-88b8-5704b331b779.png)

Beda dengan preview nya

![Screen Shot 2019-03-12 at 15 47 06](https://user-images.githubusercontent.com/48216452/54186544-38ed1200-44de-11e9-9294-54f36a2c7354.png)

**Comment by rynzvl** [comment]
fixed

**Comment by radinalsuryaatmaja** [comment]
DONE
