### ISSUE TITLE
Update Nama Sub Category - Yang sudah pasti

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#14]
ini yang sekarang : 

![Screen Shot 2019-03-12 at 22 02 30](https://user-images.githubusercontent.com/48216452/54210805-c3e7ff80-4512-11e9-93a2-3476bec2f20e.png)

Diupdate

All About GKI // Spotlight
All About GKI // People of GKI
All About GKI // Behind The Scene
Going Deeper // God's Word
Best Regards // Live Through This
Best Regards // Fiction
Art // The Works
Art // Lockscreens
Video // Praise & Worship
Video // My Story
Video // Nationality

---

Kalo bisa nama di **Menu** juga **di update** ya , mohon bantuannya

**Comment by nevrending** [comment]
Untuk mengganti nama sub-category bisa masuk ke menu Category -> Manage di backend
![image](https://user-images.githubusercontent.com/4745298/54247434-1534d500-458d-11e9-9ca1-74115a691170.png)

Lalu dibawah kolom Actions, klik tombol ![image](https://user-images.githubusercontent.com/4745298/54247450-254cb480-458d-11e9-87f5-d5999c01fc3e.png) di item category yg ingin diedit

**Comment by nevrending** [comment]
> Kalo bisa nama di Menu juga di update ya , mohon bantuannya
Bisa tlg diperjelas apa yg dimaksud dengan nama di **Menu**?

**Comment by radinalsuryaatmaja** [comment]
Menu toolbar maksudnya

![Screen Shot 2019-03-13 at 08 45 34](https://user-images.githubusercontent.com/48216452/54247668-66809c80-456c-11e9-9224-bde6b6ec9bac.png)

itu bisa dinamis diganti-ganti ?

**Comment by nevrending** [comment]
Wah kalo yg itu ngga bisa karena layout dan cara kerja link ke tiap category beda2 dan warna highlight nya beda2
![image](https://user-images.githubusercontent.com/4745298/54266273-03195d80-45b2-11e9-94f6-c38a42e2d2d4.png) 
![image](https://user-images.githubusercontent.com/4745298/54266288-0ca2c580-45b2-11e9-99fe-8525a1468c4c.png)

Bisanya di hide dulu yg belum dipake, misal Store nya mau disembunyikan dulu gitu bisa (tapi bkn lewat backend, secara code aja kita hide)

**Comment by radinalsuryaatmaja** [comment]
Maksudnya diganti secara Penamaannya saja

**Comment by nevrending** [comment]
Ooh.. Sayang nya jg ngga bisa..

**Comment by rynzvl** [comment]
yang secara dinamis cuman sub category saja.. untuk category parent diatas tidak bisa karena sudah paten secara struktur sih teknis nya begitu.. (bukan di database, tapi secara frontend),,

kurang lebih sih cara kerjanya skrg dari frontend, anggapan nya ada induk 5 parent category.. kami dari backend cuman secara coding menyesuaikan dari yang ada

**Comment by nevrending** [comment]
Closing #14
