### ISSUE TITLE
Posisi ketika ada artikel baru dan published adalah di paling kiri

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#16]
Saat ini

![Screen Shot 2019-03-13 at 00 42 11](https://user-images.githubusercontent.com/48216452/54222877-e08f3200-4528-11e9-8609-3707140ad17a.png)

seharusnya artikel radinal suryaatmaja (artikel terbaru yang di approve oleh admin) berada di **paling kiri**

**Comment by nevrending** [comment]
Fixed #16

**Comment by radinalsuryaatmaja** [comment]
done
