### ISSUE TITLE
Draft Article - Komentar - link, jumlah viewer , share , profile picture , hover mouse

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#17]
saat ini ketika user **draft article**

![Screen Shot 2019-03-13 at 00 52 55](https://user-images.githubusercontent.com/48216452/54223648-868f6c00-452a-11e9-8bfd-74b00f8b5603.png)

Harap diperhatikan

1. jumlah view share komentar bisa dikosongkan , walau dlihat bolak balik , status artikel yang masih draft , angkanya jangan bertambah

2. Jika belum ada profile picture, harap diganti dengan default . aku lihat ada aset namanya " account-circle "  , nah itu bisa dipakai . Sesegera mungkin bisa mengaktifkan upload profile picture dengan perlakuan resize small

3. itu ketika ada kalimat dikasih link , warnanya jadi putih , ... bisa ndak diganti orange , lalu ketika hover mouse orange tua

**Comment by rynzvl** [comment]
1. itu kan fungsinya buat preview ya.. jadi emg smuanya placeholder, kalau nol smua agak ga afdol juga.. kalo emg ga suka 99999 mending ntar kuganti jadi random number kyk : 134, 536, etc

2. profile picture seharusnya sudah bisa lewat accounts, bisa dicoba lewat accounts dlu.. nanti paling kita tambahin link kesana ketika foto di edit profile di click

3. itu kyknya dr css nya frontend ( detail nanti ditambah sama @nevrending )

**Comment by nevrending** [comment]
1. Atau kalo ngga di hide aja?
![image](https://user-images.githubusercontent.com/4745298/54268552-686f4d80-45b6-11e9-844a-b2c27ea93e5f.png)

2. FYI Untuk ganti prof pic lewat accounts, bkn lewat Ignite. Dan sdh bisa diganti dan sdh muncul di beberapa tempat (memang blm semua) seperti Dashboard.
Memang blm kita ganti di semuanya, karna minor dan page yg ada apa aja kayanya masih belum fix gitu ya (?) jadi biar nanti sekalian semua gitu ngganti nya.

3. Jadi begini:
![image](https://user-images.githubusercontent.com/4745298/54268672-b8e6ab00-45b6-11e9-935f-d8ca1358382b.png)
Warna putih itu dari
![image](https://user-images.githubusercontent.com/4745298/54268689-c2701300-45b6-11e9-9f95-6c3fd96bc8e3.png)
Dan style.css itu
![image](https://user-images.githubusercontent.com/4745298/54268708-cbf97b00-45b6-11e9-86f6-362488c8093c.png)

**Comment by nevrending** [comment]
Btw @radinalsuryaatmaja 

> aku lihat ada aset namanya " account-circle "

Ini dimana yah?

**Comment by nevrending** [comment]
Nvm. Point (2) fixed
![image](https://user-images.githubusercontent.com/4745298/54285735-7be1df00-45dd-11e9-87b1-49f7d45f2ae9.png)

**Comment by radinalsuryaatmaja** [comment]
1 . YES pada saat artikel user statusnya DRAFT , **hide bagian jumlah share view komen**

2. untuk nomor 2 ... barusan publishing 1 artikel , masih begini

![Screen Shot 2019-03-14 at 10 22 57](https://user-images.githubusercontent.com/48216452/54329198-3f48ce80-4643-11e9-8fb7-1a59491ef265.png)
lihat artikel terbaru , paling kiri , profile picture radinal

3. Sedang aku hubungkan ke kak andrew

**Comment by nevrending** [comment]
Point (1) dan Point (2) fixed. Mohon dicek.

Point (3) Noted

**Comment by nevrending** [comment]
@radinalsuryaatmaja 
Please confirm that Point (1) and Point (2) has been fixed and please open a separate issue for Point (3).

**Comment by nevrending** [comment]
@radinalsuryaatmaja ping

**Comment by radinalsuryaatmaja** [comment]
FIXED , nomor 3 terpisah :)
