### ISSUE TITLE
Sistem Submit Article , Edit dan Approval dari Admin/Superadmin

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#18]
jadi aku lagi buka 2 login 

1 user & 1 super admin

Nah, keadaan sekarang, 

user submit article , article yang pending di user MASIH bisa di edit , dan ternyata ngefek juga di superadmin

---

contoh artikel yang submitted
![Screen Shot 2019-03-14 at 11 08 21](https://user-images.githubusercontent.com/48216452/54330751-86d25900-4649-11e9-9617-49c05acb6110.png)

ketika kami edit di superadmin
![Screen Shot 2019-03-14 at 11 17 27](https://user-images.githubusercontent.com/48216452/54331057-d06f7380-464a-11e9-90bd-ac0a7b27aaea.png)

hasilnya sama kayak di user
![Screen Shot 2019-03-14 at 11 17 16](https://user-images.githubusercontent.com/48216452/54331070-dc5b3580-464a-11e9-90d6-24f6f73164b6.png)

----

**Harusnya** , **_kayak pendekatan sistem email_** 

ketika user submit artikel , artikel yang pending di user **TIDAK BISA DIRUBAH** oleh user

ketika di superadmin, artikel pending bisa diedit tetapi , **tidak memperlihatkan** apa yang di edit oleh superadmin

ketika udah publish oleh superadmin, barulah hasil akhirnya terlihat semua di user --> masuk ke status publish , maupun di superadmin

---

**Tambahan**

ketika artikel pending masuk superadmin , maka admin/superadmin **bisa memilih kategori dan sub categori**

![Screen Shot 2019-03-14 at 11 14 07](https://user-images.githubusercontent.com/48216452/54331163-38be5500-464b-11e9-8a07-94ae63a7a2d7.png)

**Comment by rynzvl** [comment]
1. ini emg bug, harusnya setelah pending emg ga bs di edit lagi oleh user seperti yang pernah saya tulis panjang sekali di whatsapp.. (nanti saya fix)

2. ini ga mungkin dibuat dengan sistem database yang sekarang, karena article yang dilihat user dan admin itu adalah benda yang sama, sehingga kalau  diubah di admin pasti berubah di user juga. seharusnya kalau ini dibilang dari awal sekali.. kalau mau dibuat seperti ini saya perlu rombak total database nya buat article.. jadi enaknya gimana ? apakah tetap diinginkan agar buat seperti itu ? (pembahasan lebih lanjut juga butuh @nevrending mungkin segi biaya dst )

3. harusnya bisa di edit dengan mengklik tombol "edit article", jika terjadi bug dimana setelah klik "edit article" masih tidak bisa di edit, mungkin bisa minta step2nya dimana bug tersebut bisa terjadi

**Comment by nevrending** [comment]
1. Clear yah.
3. Kalau terjadi bug, tlg di buat di issue terpisah

Next time mohon bantuannya untuk tiap2 issue dipisahkan ke thread masing2, jangan digabung seperti ini. Lebih susah nge-track nya mana yang sudah ditangani dan belum. Thank you

**Comment by nevrending** [comment]
@radinalsuryaatmaja untuk Point (1) bisa tlg dicek yah

**Comment by nevrending** [comment]
@radinalsuryaatmaja ping

**Comment by radinalsuryaatmaja** [comment]
@rynzvl @nevrending OKe , sebentar ini aku coba dan hasilnya masih sama

artikel (pending) yang di edit oleh superadmin, langsung saat itu juga update di user

enaknya gimana ??

**Comment by rynzvl** [comment]
@radinalsuryaatmaja 

no 1, coba minta screenshot lagi yang pending bisa diubah oleh user.. seharusnya sudah benar soalna di laptop saya sama yefta, gtw kalo mungkin ada beda di komputernya radinal ya


"artikel (pending) yang di edit oleh superadmin, langsung saat itu juga update di user"
-> ini ga bisa di apa2in.. sesuai dengan feature list radinal pas kita bahas sudah pernah ditulis.. pending itu cuma di edit super admin kalau emg sedikit dan langsung di approve.. kalau butuh revisi yang bnyk, alangkah baiknya menggunakan fitur "revision" biar minta user nya yang revisi sndr

![1552565194999](https://user-images.githubusercontent.com/10922027/54755085-b7049380-4c17-11e9-970a-32acbb9b3097.jpg)

kalau mau ubah saya perlu bongkar lg database dan ngubah bnyk sekali sih baik secara code maupun database, soalnya article ini core..

**Comment by nevrending** [comment]
@radinalsuryaatmaja ping

**Comment by radinalsuryaatmaja** [comment]
OKE DONE
