### ISSUE TITLE
Sub Category Video -Tidak update

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#19]
Kami telah mengedit category khususnya sub category 

lalu menambah sub category di category

tapi ada 1 sub category video yang tidak terbaca

---

ini di dashboard
![Screen Shot 2019-03-18 at 13 01 39](https://user-images.githubusercontent.com/48216452/54510012-43942500-497e-11e9-9677-dda3106a6375.png)

ini di menu
![Screen Shot 2019-03-18 at 13 01 54](https://user-images.githubusercontent.com/48216452/54512251-26fbeb00-4986-11e9-8d3f-a36d30f88be0.png)

**Comment by nevrending** [comment]
Untuk saat ini, bagian ini memang belum / sub-category masih statis

**Comment by radinalsuryaatmaja** [comment]
Tetapi untuk category ini ....

![Screen Shot 2019-03-18 at 16 06 30](https://user-images.githubusercontent.com/48216452/54518837-de4d2d80-4997-11e9-9dea-608de01e7585.png)

berubah setelah awalnya #jesussays , menjadi **God's Word**

...

Sama kayak category ini

![Screen Shot 2019-03-18 at 16 07 45](https://user-images.githubusercontent.com/48216452/54518953-050b6400-4998-11e9-9290-1294dcdd9425.png)
berubah setelah kami update name sub category di superadmin

**Comment by nevrending** [comment]
Bagian yg Video dan Art memang belum 😃

**Comment by radinalsuryaatmaja** [comment]
OALAAHHH HAHAH

**Comment by nevrending** [comment]
Fixed #19

**Comment by nevrending** [comment]
@radinalsuryaatmaja ping

**Comment by radinalsuryaatmaja** [comment]
OKE DONE
