### ISSUE TITLE
Menambahkan tulisan " Article "  pada dashboard/article - kolom menulis artikel

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#2]
Tambahkan tulisan " Article " dibawah garis pada field create article

![screen shot 2019-03-04 at 23 15 00](https://user-images.githubusercontent.com/48216452/53746377-a217c880-3ed3-11e9-8e7c-c0aa4fb57652.png)

Kalo sesuai gambar di atas, maka di taruh dengan model yang sama dengan "title slug quote"

**Comment by rynzvl** [comment]
done in commit #2, akan dimunculkan di live setelah checking dan merging ke server
