### ISSUE TITLE
Front End Error - HOME

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#20]
Ketika ada beberapa artikel di halaman HOME ...

![Screen Shot 2019-03-18 at 14 01 37](https://user-images.githubusercontent.com/48216452/54514903-e011f380-498d-11e9-93bb-98bd2fcd2c80.png)

Terlihat belum rapi , 

ada kolom yang kosong

![Screen-Shot-2019-03-18-at-14 01 37](https://user-images.githubusercontent.com/48216452/54518626-5535f680-4997-11e9-8253-43d91913ef10.png)

Mohon bisa dirapikan

**Comment by nevrending** [comment]
Mohon dijabarkan dengan sangat jelas 'rapi' itu apa sehingga tidak ambigu

**Comment by radinalsuryaatmaja** [comment]
Sudah kami update untuk issuenya, bisa dicek kembali

**Comment by nevrending** [comment]
Maksudnya bagaimana ya?

**Comment by radinalsuryaatmaja** [comment]
![Screen-Shot-2019-03-18-at-14 01 37](https://user-images.githubusercontent.com/48216452/54519180-82cf6f80-4998-11e9-9867-1b0945126a95.png)

Seharusnya tidak ada kolom kosong, 

jadi ketika ada artikel baru , selalu terisi seperti ini

![Screen-Shot-2019-03-18-at-14 01 37-2](https://user-images.githubusercontent.com/48216452/54519417-130db480-4999-11e9-9cb6-39b5fd4357db.png)

**Comment by nevrending** [comment]
Oke, seperti ini baru jelas, terimakasih untuk klarifikasinya

Penyebabnya adalah kalau title nya lebih dari 1 baris, dia akan turun
![image](https://user-images.githubusercontent.com/4745298/54520283-5705b700-49a3-11e9-895b-58cd614dbd58.png)

Kalau title nya 1 baris
![image](https://user-images.githubusercontent.com/4745298/54520266-4b19f500-49a3-11e9-9cdf-5faf9b5b77d3.png)

Kemungkinan solusinya ada 2 opsi:
1. Limit jumlah karakter pada Title yg ditampilkan jadi, misal 35 karakter, selebihnya akan ditampilkan ...
2. Perbaikan CSS, bisa menghubungi kak Andrew

**Comment by radinalsuryaatmaja** [comment]
Oke seharusnya sepanjang apapun itu judul dan quote harus bisa rapi 

Regulasinya : 

Title max 2 baris , kalo lebih kasih " ... "
Quote / Description max 3 barus , kalo lebih dikasih " ... "

---

Kak andrew bisa tolong benerin ya  (front end , CSS)

**Comment by radinalsuryaatmaja** [comment]
setelah kami memasukkan 8 artikel, front end kembali belum beres.

![Screen Shot 2019-04-11 at 18 16 14](https://user-images.githubusercontent.com/48216452/55953669-f0647800-5c86-11e9-8abb-de4787ff74d1.png)

**Comment by nevrending** [comment]
@radinalsuryaatmaja belum ada perbaikan karena kita masih menunggu kak Andrew, silahkan coba difollow up

**Comment by radinalsuryaatmaja** [comment]
iya ini sambil kami masukkan seluruh artikel terlebih dahulu juga .... sembari menunggu kak andrew

**Comment by nevrending** [comment]
@judahandrew

**Comment by judahandrew** [comment]
style.css udah aq update via bitbucket. Mohon bisa di cek and update @nevrending @radinalsuryaatmaja

**Comment by nevrending** [comment]
Fixed #20

**Comment by radinalsuryaatmaja** [comment]
belum bisa kami close karena thumbnail article pada home section Latest post masih pake yang panjang , bukan yang agak square

karena dealingnya dengan front end , .... thumbnnail home 4:3 . cover article baru 4:3 di covering jadi lebar kayak sekarang

Menunggu itu beres :))

**Comment by nevrending** [comment]
Unrelated dengan masalah di issue ini. Silahkan dibuka issue tersendiri tentang hal tsb.
