### ISSUE TITLE
Metadata untuk share ke social media , Facebook dan sejenisnya , belum jalan

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#21]
Cara kerja simplenya adalah dari pengecekan di halaman

https://developers.facebook.com/tools/debug/

, kemudian kami masukkan halaman yang udah published

https://beta.ignitegki.com/article/recharge-part-1-pejuang-yang-kehabisan-daya

Tetapi masih belum keluar image , title , desc metadata
![Screen Shot 2019-03-18 at 15 05 03](https://user-images.githubusercontent.com/48216452/54515637-3cc1de00-498f-11e9-84e3-425a6dc61303.png)

---

**Rumusnya:**

Title metadata = Titile Article
Image metadata = Thumbnail Article
description metadata = quote article

**Comment by nevrending** [comment]
Okay, ternyata tentang metadata ini belum ada di Spefisikasi 😄 

Anyway, ada beberapa hal yg perlu klarifikasi jg

Title = apakah ada format nya? Misal "IGNITE | {judul artikel}"
Url = di isi "http://www.ignitegki.com" atau link ke artikel tsb?
Site_name = tetap "IGNITE" ?

Rumus ini
> Title metadata = Title Article
> Image metadata = Thumbnail Article
> description metadata = quote article
Kan untuk article yah, untuk halaman2 lain bagaimana? Untuk halaman About misalnya

**Comment by radinalsuryaatmaja** [comment]
Oke , bisa dilihat dari artikel2 sebelumnya yang udah publish ya ...

contoh:

http://www.ignitegki.com/all-about-gki/an-upgraded-path-menggali-makna-pelayanan-melalui-camp-pembinaan-gki-klasis-banyuwangi/

di debug di developer facebook:

https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fwww.ignitegki.com%2Fall-about-gki%2Fan-upgraded-path-menggali-makna-pelayanan-melalui-camp-pembinaan-gki-klasis-banyuwangi%2F

---

Title = [Judul Artikel]
Url = [link artikel]
Site_name = [www.ignitegki.com]
description = [quote]

---

kalo untuk halaman seperti

sub category
about

atau semua yang berbassis **BUKAN ARTIKEL** , jujur belum kepikir sama sekali, bisa jadi auto scrape dari masing2 sosmed

**Comment by nevrending** [comment]
Okay, siap

Jadi untuk halaman yg bukan artikel, disamakan dengan ini aja ya
> Title = "IGNITE | In GKI We Unite"
> Description = "IGNITE merupakan wadah online bagi anak muda GKI di seluruh Indonesia. Sejak didirikan tahun 2012 lewat keberadaan majalah IGNITE, kami telah berfokus untuk memberkati sesama pemuda-pemudi GKI melalui tulisan dan karya visual lainnya. Dengan misi yang sama itulah, kini IGNITE bertransformasi dalam bentuk digital untuk tetap relevan mengikuti perkembangan jaman."
> Url = "http://www.ignitegki.com"

**Comment by nevrending** [comment]
Fixed #21

**Comment by radinalsuryaatmaja** [comment]
OKE DONE
