### ISSUE TITLE
Create Article - add image and size image - Auto fullsize

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#22]
Ada beberapa hal mengenai "kenyamanan" user  dalam menggunakan fitur create article

Pada saat add image, diharapkan sudah auto full size

contoh:

awalnya
![Screen Shot 2019-03-18 at 15 22 40](https://user-images.githubusercontent.com/48216452/54516627-0f2a6400-4992-11e9-8cb8-36dee8c62d95.png)

**diharapkan auto full size**
![Screen Shot 2019-03-18 at 15 26 47](https://user-images.githubusercontent.com/48216452/54516711-4567e380-4992-11e9-9785-981e9b5b8ab3.png)

*tetapi masih bisa dikecilkan

karena secara website sebelumnya , gambar selalu full

**Comment by nevrending** [comment]
Fixed #22

**Comment by radinalsuryaatmaja** [comment]
OKE DONE
