### ISSUE TITLE
Bagian What's Next - Error

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#24]
Front Error sepertinya , atau ada bug dengan backend , saya kurang tahu

berikut cuplikannya di halaman home beta

![Screen Shot 2019-03-21 at 10 43 11](https://user-images.githubusercontent.com/48216452/54732427-4c773780-4bc6-11e9-8c91-9cc3343e87af.png)

**Comment by nevrending** [comment]
Tentu kosong karena belum ada artikel What's Next nya sama sekali
![image](https://user-images.githubusercontent.com/4745298/54734433-61f65c80-4bda-11e9-8519-c79cb495c1f6.png)

Silahkan coba dibuat dulu beberapa artikel What's Next

**Comment by radinalsuryaatmaja** [comment]
OALAH , oke sebentar
