### ISSUE TITLE
What's Next Field - Create Article - Non aktifkan Category & Add Optional Date

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#26]
Khusus untuk bagian whats next , ada perlakuan khusus

dan setelah kami cek , ada update yang diperlukan ...

![whats-next---01](https://user-images.githubusercontent.com/48216452/54738523-3168ef80-4be7-11e9-9813-61c80b622d7b.jpg)

1. Add Optional Month
2. Non Aktifkan Category

**Comment by rynzvl** [comment]
@radinalsuryaatmaja 

1. itu saya kasih text agar bebas sih.. jadi contoh radinal mau tulis gini "January 2019" atau "Mid January"
atau mungkin mau ganti tiba2 jadi "Breaking News!" atau "HOT NEWS OF JANUARY"
cuman kalau mau diubah jadi opsi juga gpp sih.. opsinya berarti 12 ya ? january sampe desember ?

2. ini ntar saya tambahkan category what's next aja.. ntar tiap buat what's next categorynya ga ush dipilih , sudah otomatis jadi itu

**Comment by radinalsuryaatmaja** [comment]
@rynzvl oalah , begitu ... untuk nomor 1 oke deh dibuat Text aja . Untuk nomor 2 bener dibuat category whats next aja

**Comment by rynzvl** [comment]
no.2 fixed

**Comment by nevrending** [comment]
@radinalsuryaatmaja ping

**Comment by radinalsuryaatmaja** [comment]
OKE DONE
