### ISSUE TITLE
Bisa edit artikel tanpa tekan tombol edit

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#27]
awalnya

![Screen Shot 2019-03-21 at 15 08 29](https://user-images.githubusercontent.com/48216452/54739642-6bd48b80-4beb-11e9-90cd-fcd5952bfe6c.png)

kemudian kami ketik sesuatu tanpa tekan tombol edit artikel

![Screen Shot 2019-03-21 at 15 09 00](https://user-images.githubusercontent.com/48216452/54739657-7abb3e00-4beb-11e9-8088-7a81cf614414.png)

---

Harusnya sesuai dengan alur sebelumnya, user harus klik tombol edit artikel dulu

**Comment by nevrending** [comment]
Fixed #27

**Comment by radinalsuryaatmaja** [comment]
oke FIXED
