### ISSUE TITLE
Ada beberapa artikel status draft yang tidak bisa di edit

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#28]
Klik video dibawah ini

https://drive.google.com/file/d/11q-U2I5y-io6hK7haiY5UbsnTZtd54Jj/view?usp=sharing

ada artikel status draft tidak bisa di edit , ada yang bisa di edit

padahal status sama sama draft

**Comment by rynzvl** [comment]
temporarely fixed

**Comment by radinalsuryaatmaja** [comment]
oke, bentar tak cek

**Comment by nevrending** [comment]
@radinalsuryaatmaja ping

**Comment by radinalsuryaatmaja** [comment]
OKE DONE
