### ISSUE TITLE
Front End kurang sempurna dibagian sub category - All About GKI

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#29]
![Screen Shot 2019-04-01 at 15 56 19](https://user-images.githubusercontent.com/48216452/55315997-afef4800-5497-11e9-8962-375554825b37.png)

Bisa dilihat bahwa artikel BUNGA , lebarnya kurang pas

Seharusnya bisa mengikuti seperti dibawah ini

![Screen Shot 2019-04-01 at 16 06 33](https://user-images.githubusercontent.com/48216452/55316246-2d1abd00-5498-11e9-97a8-fb9b678b0f6b.png)

terimakasih

**Comment by rynzvl** [comment]
ini karena articlenya masih cuman 1 kyknya.. coba nanti ditambahin dllu di kategori yang sama hingga minimal 3 article

**Comment by radinalsuryaatmaja** [comment]
OKE, kami coba ya

**Comment by nevrending** [comment]
Closing this due to no response.
Jika dikemudian hari ingin dibahas kembali, silahkan langsung dikomen saja, tidak perlu buka issue baru.
