### ISSUE TITLE
Gambar pada field create article (dashboard) bisa ditarik sampai keluar field

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#3]
Terdapat bug seperti ini

![screen shot 2019-03-04 at 23 18 49](https://user-images.githubusercontent.com/48216452/53746606-2702e200-3ed4-11e9-97cb-dc8352d3f2cb.png)

Apakah bisa jika walau ditarik secara maksimal, gambar akan tetap pada posisi maksimalnya ? supaya tidak terkesan layoutnya rusak

**Comment by nevrending** [comment]
Fixed #3

**Comment by radinalsuryaatmaja** [comment]
DONE
