### ISSUE TITLE
Sepertinya belum ada fitur Ganti Profile Picture & Ganti Cover Profile - USER

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#30]
Belum terlihat tombol untuk ganti picture profile

![Screen Shot 2019-04-01 at 16 14 15](https://user-images.githubusercontent.com/48216452/55317484-ccd94a80-549a-11e9-9d39-2d95b5d0d169.png)

dan tombol cover thumbnail belum aktif

![Screen Shot 2019-04-01 at 16 13 52](https://user-images.githubusercontent.com/48216452/55317502-d95da300-549a-11e9-9b1f-0b51c9f250c1.png)

**Comment by nevrending** [comment]
Ganti profile picture:
Fungsi ini ada di Accounts
![image](https://user-images.githubusercontent.com/4745298/55325279-493a5080-54d0-11e9-899d-8afb54ed8e34.png)

Sudah ditambahkan tombol "Change Profile Picture" yang akan mengarahkan user ke Accounts
![image](https://user-images.githubusercontent.com/4745298/55325433-ce256a00-54d0-11e9-82a6-e368dcb9ebb2.png)

Fungsi ganti cover picture: menyusul

**Comment by nevrending** [comment]
Cover Picture: fixed #30

![image](https://user-images.githubusercontent.com/4745298/55334491-1babd200-54e5-11e9-8e24-f06e1bff7d23.png)

@radinalsuryaatmaja tlg dicek dan dicoba

**Comment by radinalsuryaatmaja** [comment]
oke, kami cek , sebentar

**Comment by radinalsuryaatmaja** [comment]
OK ADA FITURNYA
