### ISSUE TITLE
Update Profile PIcture Admin di GKI Account berbeda dengan profile

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#31]
Kami telah update profile picture

![Screen Shot 2019-04-04 at 21 04 28](https://user-images.githubusercontent.com/48216452/55562077-76c80980-571d-11e9-8342-d23dd3e1e057.png)

tetapi disini profile picture belum terupdate

![Screen Shot 2019-04-04 at 21 04 35](https://user-images.githubusercontent.com/48216452/55562110-85162580-571d-11e9-8476-c86bc8c16340.png)

**Comment by nevrending** [comment]
Profile picture (yang di Ignite) diupdate setiap kali user login.
Saya aga2 lupa tapi sepertinya dulu pernah membahas bersama mengapa didesain seperti ini dan jika tidak, dampak nya ke sistem bagaimana.

**Comment by nevrending** [comment]
Closing this due to no response.
Jika dikemudian hari ingin dibahas kembali, silahkan langsung dikomen saja, tidak perlu buka issue baru.
