### ISSUE TITLE
Default Foto User harap diganti

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#32]
Default foto saat ini

![WhatsApp Image 2019-04-05 at 09 39 23](https://user-images.githubusercontent.com/48216452/55601401-f7711f00-578a-11e9-9f3d-e727edd74200.jpeg)

harap sangat, untuk diganti dengan versi normal hehe, nanti banyak yang kaget ... hehe

versi normal icon user

**Comment by nevrending** [comment]
![image](https://user-images.githubusercontent.com/4745298/55603630-5056ac80-57b7-11e9-89c7-f3d7ac52ed05.png)

Done :)

**Comment by radinalsuryaatmaja** [comment]
![Screen Shot 2019-04-08 at 09 21 46](https://user-images.githubusercontent.com/48216452/55694760-cb9aa700-59df-11e9-8ae3-64d16d330c5f.png)

dan yang admin masih sama ?? atau error ??

**Comment by nevrending** [comment]
![image](https://user-images.githubusercontent.com/4745298/55697175-7a9caa00-5a03-11e9-8a09-4fcaf18e160a.png)

Fixed
Efek kemarin implement FB & Google login

**Comment by radinalsuryaatmaja** [comment]
oke done
