### ISSUE TITLE
Double Posting Article at HOME - section latest post

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#33]
kami barusan posting 3 artikel dari ADMIN

dan hasil HOME nya seperti ini

![Screen Shot 2019-04-08 at 09 21 04](https://user-images.githubusercontent.com/48216452/55694846-2e8c3e00-59e0-11e9-8239-d154d3f6ff55.png)

aku scrool ke bawah

![Screen Shot 2019-04-08 at 09 21 08](https://user-images.githubusercontent.com/48216452/55694860-3ba92d00-59e0-11e9-9a11-6720f33f3587.png)

error kah ???

**Comment by nevrending** [comment]
Ada error dari slider nya (Frontend)
![image](https://user-images.githubusercontent.com/4745298/55697200-9ef88680-5a03-11e9-9c65-4a7d3129826f.png)

**Comment by rynzvl** [comment]
sudah ku tutup dlu..
mungkin bisa tambahin slider nya dlu 1 foto gitu @radinalsuryaatmaja

**Comment by radinalsuryaatmaja** [comment]
oke, ....

**Comment by nevrending** [comment]
Closing this due to resolved.
Untuk masalah di slider nya, silahkan buka issue baru.
