### ISSUE TITLE
Menambahkan Tombol Delete pada Whats's Next

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#35]
Sepertinya harus ditambah fungsi delete pada bagian whats next

Yang ada saat ini pilihannya

![Screen Shot 2019-04-11 at 18 26 50](https://user-images.githubusercontent.com/48216452/55953960-a6c85d00-5c87-11e9-848a-0312eec76d05.png)

**Comment by rynzvl** [comment]
@radinalsuryaatmaja yang ini sudah bisa di coba untuk tombol deletenya, maaf lama

**Comment by radinalsuryaatmaja** [comment]
OKE DONE
