### ISSUE TITLE
Penggantian nama dari GKI ACCOUNT menjadi IGNITE GKI ACCOUNT

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#36]
Mohon seluruh nama yang bersangkutan di bagian login/ register , my profile dari ...

GKI ACCOUNT , berubah menjadi IGNITE GKI ACCOUNT

supaya tidak terlihat membingungkan bagi para user

TErimakasih

**Comment by radinalsuryaatmaja** [comment]
Termasuk yang ini

![Screen Shot 2019-04-12 at 15 44 05](https://user-images.githubusercontent.com/48216452/56027372-2154b380-5d40-11e9-8922-0147686b9605.png)

Default name title user dari GKI IGNITE menjadi IGNITE GKI

**Comment by nevrending** [comment]
Akan ada biaya tambahan ya.
Dikarenakan sudah sejak lama seperti ini dan di spesifikasi juga demikian

**Comment by radinalsuryaatmaja** [comment]
boleh diajukan ...

**Comment by nevrending** [comment]
Quotation sudah diemailkan

Untuk yg IGNITE GKI sudah selesai
![image](https://user-images.githubusercontent.com/4745298/56029171-667ee280-5d4c-11e9-85d7-0126ec9d8256.png)
