### ISSUE TITLE
Pada Saat Log Out lama dan ketika kembali login, sudah auto login - mungkin ini error

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#37]
Bisa dilihat videonya di sini

https://drive.google.com/file/d/1cF1bGBpbydlYRDRnJQH_iVeYg0KiPza8/view?usp=sharing

Terimakasih

**Comment by nevrending** [comment]
Karena Ignite dan Accounts adalah 2 sistem/aplikasi yang berbeda, jadi ketika logout di Ignite, tidak logout di Accounts juga. Namun masa aktif login di Accounts adalah 15 menit, stelah 15 menit berlalu dan tidak ada aktivitas (di Accounts), user akan otomatis terlogout dari Accounts.

Jika tujuannya adalah untuk ganti user, saya pernah sampaikan di group tanggal 1 April 2019:
> Untuk logout dan ganti user, setelah logout dari ignite, pergi ke accounts.ignitegki.com dan logout disana jg
Nanti untuk user hal ini harusnya tidak masalah karena user kecil kemungkinannya punya 2 account (kecil kemungkinan user perlu gonta ganti account)

**Comment by radinalsuryaatmaja** [comment]
Tetapi secara end user atau UX nya , kami hanya mendapati tombol log out untuk IGNITE saja , belum sampai pada accountsnya. Sehingga presepsi orang , jika kami pencet log out yang ada sekarang dalam menu atau dashboard user ignite , maka kami 100% telah keluar , tetapi harusnya dia juga log out account kan , cuma log out account ndak nampak di user. Takutnya UX nya ndak pas disini dan user bisa bingung.

atau jika berkenan, tombol log out dimanapun itu adalah log out ignite dan account

**Comment by nevrending** [comment]
>Sehingga presepsi orang , jika kami pencet log out yang ada sekarang dalam menu atau dashboard user ignite , maka kami 100% telah keluar

Nah jika orang sudah berpersepsi seperti itu, berarti sudah benar kan.
Bingung gimana ya?
Disisi lain bukankah lebih praktis juga kalo setelah logout, ternyata perlu segera login lagi, tinggal klik login sudah masuk?

> tetapi harusnya dia juga log out account kan

Tidak harus. Akan otomatis terlogout setelah 15 menit.

Nanti kan user juga tidak perlu ganti account karena ketika misal dia sudah diberikan kemampuan editor, dia tetap bisa menulis artikel layaknya user biasa dan melakukan kegiatan editor dengan account yg sama.

---

> atau jika berkenan, tombol log out dimanapun itu adalah log out ignite dan account

Sayang nya hal ini tidak memungkinkan.. Karena mereka berdiri sendiri2.
Yg bisa dilakukan mgkn mempersingkat masa aktif loginnya dari 15 menit jadi 5 menit gitu.

**Comment by radinalsuryaatmaja** [comment]
berarti cara kerja berbeda kayak google ya ?

setahuku, ketika kita login di google account , baru kita bisa gunakan fitur drive , youtube dll.
Kemudian, sekali kita logout dari drive, youtube dan kawan2 , kita bener2 100% logout dari semua fitur google , dan jika mau masuk lagi kita bener2 harus login dari awal

ilustrasi ini kupakai karena ide account terpisah seperti google adalah dari rekan2 developer, sehingga kami merasa, o itu oke.

**Comment by nevrending** [comment]
Merged with #41
