### ISSUE TITLE
Hide Admin, Superadmin, Editor, User dalam Top Contributor pada dashboard USER

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#38]
Bisa kah jika kita SEBAGAI USER , hanya bisa melihat sesama USER saja ...

jadi Admin , Superadmin , Editor, User tidak terlihat di user

![Screen-Shot-2019-04-12-at-15 59 44](https://user-images.githubusercontent.com/48216452/56028917-6fb78180-5d43-11e9-9606-e94abb1c51b4.jpg)

**Comment by nevrending** [comment]
Yang bisa kita lakukan adalah hide user bawaan (Superadmin, Admin, Editor, User) dari Top Contributor dan New Contributors dari semua dashboard. Kalo dibedakan jadi hanya tidak muncul di tampilan user aja, aga lumayan. Bagaimana?

**Comment by radinalsuryaatmaja** [comment]
Yes , 

jadinya ketika user login , ....

top contributor dan new contributor adalah hanya USER USER yang registrasi di IGNITE ya ...

**Comment by nevrending** [comment]
Oke, done

Fixed #38

**Comment by radinalsuryaatmaja** [comment]
OKE DONE
