### ISSUE TITLE
Hide nama gereja di profile user

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#39]
Hide untuk sementara dulu

![20190429-nama gereja hilangkan](https://user-images.githubusercontent.com/48216452/56887180-15385800-6a9b-11e9-8f04-f6bfda309545.jpeg)

**Comment by nevrending** [comment]
Fixed #39

**Comment by radinalsuryaatmaja** [comment]
OKE DONE
