### ISSUE TITLE
Masalah pada create article field - Alternative Text - Frola Editor

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#4]
**Perhatikan baik-baik gambar dibawah ini:**

ketika gambar diperkecil
![screen shot 2019-03-04 at 23 31 16](https://user-images.githubusercontent.com/48216452/53747360-a9d86c80-3ed5-11e9-8c2f-fe7f4395d793.png)

ketika gambar di klik lalu pilih alternative text

![screen shot 2019-03-04 at 23 33 37](https://user-images.githubusercontent.com/48216452/53747532-0cca0380-3ed6-11e9-84bc-5bc6aab43eb4.png)

![screen shot 2019-03-04 at 23 33 45](https://user-images.githubusercontent.com/48216452/53747550-17849880-3ed6-11e9-9f6e-18e3bf6ec653.png)

tidak terjadi apa apa

![screen shot 2019-03-04 at 23 34 02](https://user-images.githubusercontent.com/48216452/53747565-1f443d00-3ed6-11e9-8afc-a5f8b82a0185.png)

Bisa aktifkan fitur ini ? jika tidak bisa , hapus fitur ini

**Comment by rynzvl** [comment]
@radinalsuryaatmaja fitur ini jalan kok, biasanya dipakai untuk SEO radinal.. jadi emg tidak muncul di browser.. satu2nya saat akan muncul di browser adalah ketika gambarnya error.. maka akan muncul tulisan alternative nya seperti contoh dibawah ini : 
![alt](https://user-images.githubusercontent.com/10922027/53775232-47f32380-3f24-11e9-9a6a-b0ab3100bf9d.JPG)

**Comment by radinalsuryaatmaja** [comment]
oalah, soalnya tadi ngetestnya alternative text ketika pake image caption

OKE OKE
