### ISSUE TITLE
Submit dan belum lengkap pada saat create article, diharapkan tidak kembali dari nol

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#40]
Untuk yang sekarang ini

https://drive.google.com/file/d/1o2ampJzfm3hpDcXUQnmI7n-UZwS2N-AZ/view?usp=sharing

---

diharapkan tidak reload ulang karena jika penulis sudah menulis panjang lalu SUBMIT tapi lupa mengisi field yang kosong , maka apa yang dikerjakan akan kembali dari 0

mungkin bisa dibuat checking nya tidak reload , sehingga tulisan yang telah dikerjakan, tidak hilang

terimakasih

**Comment by nevrending** [comment]
@rynzvl #48

**Comment by rynzvl** [comment]
ah iya, validasinya nge bug kalo dilakukan di submit.
sudah Fixed, bisa dicoba lagi @radinalsuryaatmaja

**Comment by nevrending** [comment]
Closing this due to no response.
Jika dikemudian hari ingin dibahas kembali, silahkan langsung dikomen saja, tidak perlu buka issue baru.
