### ISSUE TITLE
Saran untuk USER untuk bisa logout 100% dari IGNITE GKI dan ACCOUNT

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#41]
Tombol logout saat ini , sebagai user, **hanya terlihat pada**

https://beta.ignitegki.com/ignite/dashboard

di halaman tersebut tidak ditemukan button atau tanda menuju link

https://accounts.ignitegki.com/profile

jadi user bingung

....

karena kedua platform tersebut adalah terpisah , maka aku berpikir **keras** haha, piye ya, supaya user ini bener2 bisa logout 100% , karena tim konten "komplainnya" gt , kok ndak isa logout ya ??

...

nah kemudian aku berpikir dengan fitur & cara ini

![Screen Shot 2019-04-29 at 17 09 02](https://user-images.githubusercontent.com/48216452/56889854-db1e8480-6aa1-11e9-8df3-32ed0da1db62.png)

ada tombol **IGNITE GKI ACCOUNT** untuk masuk ke https://accounts.ignitegki.com/profile

ditaruh di menu pada gambar icon user auto breakdown ada submenu IGNITE GKI ACCOUNT

**Comment by nevrending** [comment]
Baru saja implement sesuatu cara, silahkan dicoba logout dari Ignite lalu langsung klik login lagi.

Fixed #41

**Comment by radinalsuryaatmaja** [comment]
Malam ini

Jumat, 03 Mei 2019 di cek

masih sama seperti sebelumnya

video amatirnya

https://drive.google.com/file/d/1dXEhllS7kI6ycrr4W31BB5h3zhvJXQO-/view?usp=sharing

Makasih

**Comment by nevrending** [comment]
Login nya menggunakan apa? Email-Password atau Facebook atau Google?

**Comment by nevrending** [comment]
Nevermind, silahkan dicoba lagi.

**Comment by radinalsuryaatmaja** [comment]
> Login nya menggunakan apa? Email-Password atau Facebook atau Google?

sementara ini diriku login by google

---

Untuk saat ini udah bisa logout dan ketika kursor ke icon account , keluar tulisan LOGIN dan ketika di klik masuk ke halaman login ignite

tapi ketika kami klik Google kembali , maka sudah auto login kembali dengan user sebelumnya

berikut videonya:

https://drive.google.com/file/d/1a9T4A4V_VIz5aWscAZfdk48fopTh2UqM/view?usp=sharing

ini sama dengan sistem hipwee dan masih normal

**Comment by nevrending** [comment]
> tapi ketika kami klik Google kembali , maka sudah auto login kembali dengan user sebelumnya

Tentu, karena login di google nya masih aktif. Jika ingin login pakai account google yg lain, harus logout dulu dengan pergi ke account.google.com atau semacam nya. FYI aja kita nda bisa buat itu autologout karena sudah bukan ranah kita, itu ranah nya google.
