### ISSUE TITLE
Ganti Nama , WHAT'S NEXT --> EDITOR'S LETTER

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#42]
Halaman HOME , di section WHAT'S NEXT , maaf harus dirubah namanya menjadi EDITOR'S LETTER

Seperti kami merubahnya di inspect , dibawah ini

![Screen Shot 2019-04-29 at 17 59 22](https://user-images.githubusercontent.com/48216452/56892181-0789cf00-6aa9-11e9-88cd-4aff4d84c15f.png)

Makasih

**Comment by nevrending** [comment]
Fixed  #42

**Comment by radinalsuryaatmaja** [comment]
DONE
