### ISSUE TITLE
Ganti nama what's next --> Editor's Letter (pada dashboard admin)

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#43]
Bisa diganti namanya dan telah kami coba menggunakan inspect

<img width="457" alt="Screen Shot 2019-05-07 at 10 31 52" src="https://user-images.githubusercontent.com/48216452/57269903-812a4a00-70b3-11e9-9ba0-ce8aa81123ba.png">

terimakasih

**Comment by nevrending** [comment]
Fixed #43

**Comment by radinalsuryaatmaja** [comment]
done
