### ISSUE TITLE
Pemindahan Menu pada dashboard user dan admin (bagian events)

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#44]
untuk Admin

<img width="397" alt="Screen Shot 2019-05-07 at 10 34 17" src="https://user-images.githubusercontent.com/48216452/57270119-3ceb7980-70b4-11e9-9a24-95974c9346e5.png">

Untuk user

<img width="386" alt="Screen Shot 2019-05-07 at 10 37 06" src="https://user-images.githubusercontent.com/48216452/57270145-58568480-70b4-11e9-93d4-e75773ecc67f.png">

---

Alasannya karena main productnya IGNITE adalah karya digital

terimakasih

**Comment by nevrending** [comment]
Fixed #44

**Comment by radinalsuryaatmaja** [comment]
done
