### ISSUE TITLE
Menambah fitur Delete di manage all article pada admin

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#46]
Mampu menghapus artikel yang pending atau published

letak bisa dberikan tanda silang di sebelah icon edit (dibawah ini)

<img width="1327" alt="Screen Shot 2019-05-07 at 12 48 01" src="https://user-images.githubusercontent.com/48216452/57274799-9492e080-70c6-11e9-8e45-8114431b7ceb.png">

dan

di dalam edit article yang pending atau published

<img width="1770" alt="Screen Shot 2019-05-07 at 12 50 15" src="https://user-images.githubusercontent.com/48216452/57274851-b55b3600-70c6-11e9-8b10-ed5a5a2d179b.png">

terimakasih

**Comment by rynzvl** [comment]
@radinalsuryaatmaja sudah kutambahkan. kalau bisa, tolong di bantu cek2 lagi juga ya.. takutnya bisa kena bug entah dimana. kalau ada apa2 langsung comment aja disini
