### ISSUE TITLE
Error ketika semua field pada create post belum terpenuhi (untung di previous data masih ada)

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#48]
lihat video dibawah ini

https://drive.google.com/file/d/1EuASz_mrK50A4K11ugLmiS9izS58SiaT/view?usp=sharing

cukup kaget bagi user

untung di back masih ada

---

diharapkan ketika belum lengkao , harus ada alert ya.

makasih

**Comment by nevrending** [comment]
Merged in #40
