### ISSUE TITLE
User dan admin tidak bisa logout

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#49]
Admin Tidak bisa logout

https://drive.google.com/file/d/1MaJnlG8o-tGvM07GpihN8v08QiR-rCsj/view?usp=sharing

---

User tidak bisa logout

https://drive.google.com/file/d/1RkZNWre0W4ccwcLC6b-nb1JVzMCApjgI/view?usp=sharing

---

Menggunakan laptop Apple macbook pro 2018, Radinal

**Comment by nevrending** [comment]
Try fix #49

Aku nda bisa replicate error yg sama, tapi aku coba ubah2 sesuatu.
Silahkan dicoba2 lagi, kalo masih terjadi, kemungkinan hanya terjadi di laptop Radinal.

**Comment by nevrending** [comment]
Closing this due to no response.
Jika dikemudian hari ingin dibahas kembali, silahkan langsung dikomen saja, tidak perlu buka issue baru.
