### ISSUE TITLE
Masalah pada create article field - Aligment - Frola Editor

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#5]
Aligment gambar diganti ke right pada field create article, tidak terjadi apa apa

![screen shot 2019-03-04 at 23 43 45](https://user-images.githubusercontent.com/48216452/53748174-667efd80-3ed7-11e9-94a8-7b448198218e.png)

walau ketika di save, gambar di halaman artikelnya sudah aligment right

![screen shot 2019-03-04 at 23 47 32](https://user-images.githubusercontent.com/48216452/53748469-f91f9c80-3ed7-11e9-8254-7c2b4af17288.png)

**Comment by nevrending** [comment]
Fixed #5

**Comment by radinalsuryaatmaja** [comment]
DONE
