### ISSUE TITLE
Masalah pada create article field - Image Caption - Frola Editor

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#6]
Gambar sebelum di klik image caption

![screen shot 2019-03-04 at 23 55 25](https://user-images.githubusercontent.com/48216452/53749103-3f293000-3ed9-11e9-8e83-0886c881d334.png)

Ketika di klik image caption, tiba-tiba besar sendiri , seharusnya tetap
Lalu opsi/fitur pada image caption terlalu banyak , karena image caption hanya butuh 

bold , italic , underline , strikethorugh , opsi aligment (sesuai width gambar) , font size , colours , font family

Terutama aligment , fitur tersebut tidak berjalan baik pada saat di field create article

![screen shot 2019-03-04 at 23 55 42](https://user-images.githubusercontent.com/48216452/53749125-4c461f00-3ed9-11e9-8430-2a31bc8cca16.png)

Lalu ketika di klik seperti dibawah ini. Mungkin ini bug. Ketika image caption aktif pada gambar, fungsi fitur tidak berjalan dengan sempurna

Jika di klik gambar, maka fungsi resize aktif
Jika di klik caption gambar , fitur caption aktif

![screen shot 2019-03-05 at 00 07 49](https://user-images.githubusercontent.com/48216452/53750106-86182500-3edb-11e9-913c-a6acdb273994.png)

**Comment by nevrending** [comment]
Fixed #6


> Lalu opsi/fitur pada image caption terlalu banyak , karena image caption hanya butuh
> bold , italic , underline , strikethorugh , opsi aligment (sesuai width gambar) , font size , colours , font family

Untuk button2 nya yg ini ngikut setting utama editornya.
Udah ku cari2 dan ternyata ga bisa disetting sendiri2 editor nya ada button apa aja, image caption ada button apa aja gitu.

**Comment by radinalsuryaatmaja** [comment]
DONE
