### ISSUE TITLE
As User - Error - SUBMIT Article to Admin

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#8]
User sudah tulis artikel , tetap bagian bawah **hanya keluar tombol** , save as draft 

setahu kami ada tombol , Sent (Sent to admin& pending status di superadmin)

![Screen Shot 2019-03-12 at 10 04 10](https://user-images.githubusercontent.com/48216452/54171827-54d8bf80-44ae-11e9-8dd2-97eb4dd32c90.png)

Kemudian setelah kami tulis, dan klik save as draft, muncul bug error

![Screen Shot 2019-03-12 at 10 01 22](https://user-images.githubusercontent.com/48216452/54171857-746fe800-44ae-11e9-8c59-70ad32e28ecf.png)

Catatan:

Kami menggunakan file image dengan resolusi asli dalam pembuatan artikelnya . Ini dibuat supaya memfasilitasi user lain yang pasti seperti itu. Sehingga fitur auto resize image dalam artikel wajib ada, supaya artikel tidak berat

**Comment by rynzvl** [comment]
oh iya saya lupa.. kalau pertama kali buat article emang jadi "draft" dlu.. jadi ga langsung di send ke admin (user masih bisa edit lg kapan2), kalau sudah oke nanti muncul tombol send..

untuk errornya itu sepertinya category nya belum dipilih.. sebentar ya ini saya fix dlu untuk tambahin pengaman agar category nya dipilih..

**Comment by radinalsuryaatmaja** [comment]
atau lebih baik ditambahkan saja tombol SENT sekalian, sehingga user bisa pilih:

1. kalo masih draft, bisa tekan draft
2. kalo sudah yakin walau pertama kali create article , bisa difasilitasi

**Comment by rynzvl** [comment]
ok

**Comment by radinalsuryaatmaja** [comment]
maaf , kata SENT diganti

**SUBMIT**

**Comment by rynzvl** [comment]
fixed + updated tombol submit langsung, coba ditest lg dalam 5 menit (lg di update di server).
kalau sudah benar, minta di "close and comment". thanks

**Comment by radinalsuryaatmaja** [comment]
DONE
